// Generated by CoffeeScript 1.10.0
(function() {
  var _, jade,
    slice = [].slice;

  jade = require('jade');

  _ = require('lodash');

  exports.BootstrapReactApp = function(assetPath, $req, $res) {
    var $d, react;
    react = require("react");
    $d = react.DOM;
    return function(reactAppFactory, javascriptLocation, stylesheetLocation, initialState) {
      var body, head, html, initialStateJson;
      initialStateJson = JSON.stringify(initialState, function(key, value) {
        if (value instanceof RegExp) {
          return value.toString();
        }
        return value;
      });
      head = $d.head.apply($d, [{}].concat(slice.call([
        $d.link({
          rel: "shortcut icon",
          href: assetPath("favicon.ico")
        }), $d.link({
          rel: "stylesheet",
          type: "text/css",
          href: assetPath(stylesheetLocation)
        }), $d.meta({
          name: "viewport",
          content: "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=1"
        }), $d.meta({
          name: "mobile-web-app-capable",
          content: "yes"
        }), $d.meta({
          name: "apple-mobile-web-app-capable",
          content: "yes"
        }), $d.meta({
          name: "mobile-web-app-status-bar-style",
          content: "black-translucent"
        }), $d.meta({
          name: "apple-mobile-web-app-status-bar-style",
          content: "black-translucent"
        }), $d.script({
          id: "initial-state",
          type: 'application/json',
          dangerouslySetInnerHTML: {
            __html: initialStateJson
          }
        })
      ])));
      body = $d.body.apply($d, [{
        style: {
          width: '100%',
          height: '100%'
        }
      }].concat(slice.call([
        $d.section({
          id: "app"
        }), $d.script({
          type: "application/javascript",
          src: assetPath('jquery.js')
        }), $d.script({
          type: "application/javascript",
          src: assetPath('jquery.autogrow.js')
        }), $d.script({
          type: "application/javascript",
          src: assetPath('jquery.resize.js')
        }), $d.script({
          type: "application/javascript",
          src: assetPath('client/common_libs.js')
        }), $d.script({
          type: "application/javascript",
          src: assetPath(javascriptLocation)
        }), $d.div({
          dangerouslySetInnerHTML: {
            __html: jade.renderFile('views/layouts/external_scripts.jade', _.merge({
              app: true
            }, $res().locals)).toString()
          }
        })
      ])));
      html = $d.html.apply($d, [{}].concat(slice.call([head, body])));
      return react.renderToStaticMarkup(html);
    };
  };

}).call(this);

//# sourceMappingURL=react_compiler.js.map
