// Generated by CoffeeScript 1.10.0
(function() {
  exports.ZendeskApi = function($p, $options) {
    var client, convertError, self, zendesk;
    zendesk = require('node-zendesk');
    client = zendesk.createClient($options);
    convertError = {
      error: function(err) {
        var e, errData, error, message, ref, ref1;
        if (err.result != null) {
          try {
            errData = JSON.parse(err.result.toString());
            message = (errData != null ? (ref = errData.error) != null ? ref.message : void 0 : void 0) || (errData != null ? (ref1 = errData.error) != null ? ref1.title : void 0 : void 0) || errData.details || errData;
          } catch (error) {
            e = error;
          }
        }
        return $p.error(message || err);
      }
    };
    return self = {
      createTicket: function(userName, ipAddress, userAgent, accountIdentifier, emailAddress, message) {
        var ticket;
        ticket = {
          ticket: {
            subject: message,
            description: message,
            requester: {
              name: userName,
              email: emailAddress,
              locale_id: 8
            },
            custom_fields: {
              userName: userName,
              32087307: ipAddress,
              32060098: userAgent,
              32060298: accountIdentifier
            }
          }
        };
        return $p.wrap(client.tickets.create(ticket, $p.ecb())).then(convertError).then(function() {});
      }
    };
  };

}).call(this);

//# sourceMappingURL=zendesk.js.map
