// Generated by CoffeeScript 1.10.0
(function() {
  var LandingPage, React, props;

  React = require('react');

  LandingPage = require('../components/app');

  props = JSON.parse(document.getElementById('initial-state').innerHTML);

  React.render(LandingPage(props), document.getElementById('app'));

}).call(this);

//# sourceMappingURL=app_client.js.map
