// Generated by CoffeeScript 1.10.0
(function() {
  var React, ReactCanvas, _;

  React = require('react');

  ReactCanvas = require('react-canvas');

  _ = require('lodash');

}).call(this);

//# sourceMappingURL=common_libs.js.map
