// Generated by CoffeeScript 1.10.0
(function() {
  var _, _messages;

  _ = require('lodash');

  _messages = null;

  module.exports = function(key, parameters) {
    var message;
    if (_messages == null) {
      throw new Error("Locale has not been initialized yet");
    }
    message = _messages;
    _.map(key.split('.'), function(part) {
      return message = message != null ? message[part] : void 0;
    });
    if (((typeof console !== "undefined" && console !== null ? console.error : void 0) != null) && (message == null)) {
      console.error("Locale: Key [" + key + "] not found");
    }
    return message;
  };

  module.exports.setMessages = function(messages) {
    return _messages = messages;
  };

}).call(this);

//# sourceMappingURL=locale.js.map
