// Generated by CoffeeScript 1.10.0
(function() {
  var $l, React, _, createFactory, d;

  _ = require('lodash');

  React = require('react');

  d = _.merge(React.DOM, require('./common'), require('./canvas'));

  createFactory = d.createFactory;

  $l = require('./locale');

  module.exports = createFactory({
    getInitialState: function() {
      return {
        message: ""
      };
    },
    show: function(animate) {
      return this.refs.dialog.show(animate);
    },
    handleCancel: function() {
      this.replaceState(this.getInitialState());
      return this.refs.dialog.hide();
    },
    handleSubmit: function() {
      return this.props.restClient.post('/support', this.state, (function(_this) {
        return function(result) {
          _this.handleCancel();
          if (result.confirmation != null) {
            return alert(result.confirmation);
          }
        };
      })(this));
    },
    handleChange: function(e) {
      var field, value;
      value = $(e.target).val();
      field = $(e.target).attr('name');
      return this.setState(_.object([[field, value]]));
    },
    render: function() {
      return d.ModalDialog({
        ref: 'dialog',
        className: 'support'
      }, d.h4({}, "How can we help you?"), d.textarea({
        name: 'message',
        value: this.state.message,
        placeholder: 'Type your message here',
        onChange: this.handleChange
      }), d.div({
        className: 'buttons'
      }, d.Button({
        onClick: this.handleCancel
      }, "Cancel"), d.Button({
        onClick: this.handleSubmit
      }, "Submit")));
    }
  });

}).call(this);

//# sourceMappingURL=support.js.map
